run:
	go run shortform.go longform.go multipleDeclaration.go variables.go fmt.go gettingStarted.go statementsAndExpressions.go zeroValues.go operators.go main.go

build:
	go build -o day01 shortform.go longform.go multipleDeclaration.go variables.go fmt.go gettingStarted.go statementsAndExpressions.go zeroValues.go operators.go main.go