run:
	go run inferred.go longform.go shortform.go multiDeclaration.go main.go typeEfficiency.go grouping.go

build:
	go build -o day02 inferred.go longform.go shortform.go multiDeclaration.go main.go typeEfficiency.go grouping.go